# Generated by Django 2.0.6 on 2020-02-11 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0016_auto_20200124_1012'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=256)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Candidate', to='candidate.Candidate')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Client', to='clients.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_round', models.CharField(choices=[('FR', 'Online round'), ('SR', 'Technical round'), ('TR', 'HR round')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewStatus',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('FS', 'Processing'), ('SS', 'Completed'), ('TS', 'Sheduled')], default='FS', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_round_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='InterviewRound', to='interviews.InterviewRound'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='InterviewStatus', to='interviews.InterviewStatus'),
        ),
        migrations.AddField(
            model_name='interview',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Job', to='clients.Job'),
        ),
        migrations.AddField(
            model_name='interview',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
