# Generated by Django 2.0.6 on 2019-06-29 10:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=512)),
                ('web_link', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('headquarter', models.CharField(default=None, max_length=512)),
                ('address', models.CharField(default=None, max_length=1024)),
                ('category', models.CharField(choices=[('private', 'PRIVATE'), ('public', 'PUBLIC')], default='private', max_length=256)),
                ('business_type', models.CharField(choices=[('product', 'PRODUCT'), ('service', 'SERVICE'), ('hybrid', 'HYBRID')], default='product', max_length=256)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=256)),
                ('profile_desc', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('aggrement_doc', models.CharField(default=None, max_length=1024)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
            ],
            options={
                'db_table': 'api_client',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(default=None, max_length=512)),
                ('jd_url', models.CharField(default=None, max_length=1024)),
                ('tech_skills', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('job_type', models.CharField(choices=[('permanent', 'PERMANENT'), ('contract', 'CONTRACT'), ('part_time', 'PART_TIME')], default='permanent', max_length=256)),
                ('min_exp', models.IntegerField(default=0)),
                ('max_exp', models.IntegerField(default=60)),
                ('min_relevant_exp', models.IntegerField(default=0)),
                ('max_notice', models.IntegerField(default=60)),
                ('min_ctc', models.FloatField(default=0.0)),
                ('max_ctc', models.FloatField(default=1000.0)),
                ('expiring_days', models.IntegerField(default=180)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('on_hold', 'ON_HOLD'), ('expiried', 'EXPIRED')], default='active', max_length=256)),
                ('jd_extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='clients.Client')),
            ],
            options={
                'db_table': 'api_job',
            },
        ),
    ]
