# Generated by Django 2.0.6 on 2019-12-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jd_url',
            field=models.CharField(blank=True, default=None, max_length=1024),
        ),
    ]
