# Generated by Django 2.0.6 on 2020-06-10 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200211_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientcategory',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_category', models.CharField(choices=[('PB', 'Public'), ('PR', 'Private'), ('OT', 'Other')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clientindustry',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_industry', models.CharField(choices=[('FN', 'Finance'), ('RS', 'Resources'), ('PD', 'Products'), ('HP', 'Health and public')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='category',
        ),
        migrations.RemoveField(
            model_name='client',
            name='extra',
        ),
        migrations.AddField(
            model_name='client',
            name='ceo',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='client',
            name='founded_on',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='client',
            name='founder',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='client',
            name='latest_funding',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='client',
            name='revenue',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('on_hold', 'ON_HOLD'), ('expiried', 'EXPIRED')], default='active', max_length=256),
        ),
        migrations.AddField(
            model_name='client',
            name='Clientcategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='clients.Clientcategory'),
        ),
        migrations.AddField(
            model_name='client',
            name='clientindustry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='industry', to='clients.Clientindustry'),
        ),
    ]
