# Generated by Django 2.0.6 on 2019-12-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_candidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
